services:
    client:
        class: Silktide\FreshdeskApi\Client
        arguments:
          - "@guzzle"
          - "@responseFactory"
          - "@interpolator"
          - "%freshdeskDomain%"
          - "%usernameOrToken%"
          - "%password%"

    guzzle:
        class: GuzzleHttp\Client
    responseFactory:
        class: Silktide\FreshdeskApi\ResponseFactory
    stringifier:
        class: mef\Stringifier\Stringifier
    interpolator:
        class: mef\StringInterpolation\PlaceholderInterpolator
        arguments:
          - "@stringifier"

arguments:
    freshdeskDomain:
    usernameOrToken:
    password:
